### ISSUE TITLE
安装visual-environment

### ISSUE THREAD

**Issue by withqingshao** [alibaba/virtual-environment#17]
2020-06-25T06:00:16.035236Z    info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates

**Comment by linfan** [comment]
能提供一下所用的Kubernetes和Istio版本，以及其他环境情况吗（比如当前集群中一共创建了多少个VirtualEnvironment对象）？
另外麻烦尝试下按文档里”[流量未自动加环境标](https://alibaba.github.io/virtual-environment/#/zh-cn/ve/trouble-shooting?id=%e6%b5%81%e9%87%8f%e6%9c%aa%e8%87%aa%e5%8a%a8%e5%8a%a0%e7%8e%af%e5%a2%83%e6%a0%87)“部分所述的步骤，查看一下出问题的时候Envoy容器日志中是否有什么异常信息？

这个现象比较可能是由于EnvoyFilter配置导致的。
在配置启用`envHeader.autoInject: true`的时候，visual-environment控制器会在所在的Namespace内注册一个EnvoyFilter对象，用于自动为所有“不带环境标的HTTP请求”增加其所处Pod的虚拟环境的环境标Header。这个EnvoyFilter对象正常情况下不应该影响Envoy与Pilot的通信，但之前也有用户反馈过出现类似情况。
我们在自己的集群里使用Istio 1.4/1.5/1.6都进行过验证，至今尚未复现此问题。

可尝试在创建VirtualEnvironment对象的时候，将配置`envHeader.autoInject`的值设置为`false`，重新apply到集群，看看问题是否消失。等待亲的反馈~

**Comment by withqingshao** [comment]
改成false就可以了，我是docker desktop&nbsp; k8s 1.65&nbsp; ,istio 1.5.2版本


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fan Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月25日(星期四) 晚上9:16
收件人:&nbsp;"alibaba/virtual-environment"<virtual-environment@noreply.github.com&gt;;
抄送:&nbsp;"张绍青"<1311204171@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/virtual-environment] 安装visual-environment (#17)





 
能提供一下所用的Kubernetes和Istio版本，以及其他环境情况吗（比如当前集群中一共创建了多少个VirtualEnvironment对象）？
 另外麻烦尝试下按文档里”流量未自动加环境标“部分所述的步骤，查看一下出问题的时候Envoy容器日志中是否有什么异常信息？
 
这个现象比较可能是由于EnvoyFilter配置导致的。
 在配置启用envHeader.autoInject: true的时候，visual-environment控制器会在所在的Namespace内注册一个EnvoyFilter对象，用于自动为所有“不带环境标的HTTP请求”增加其所处Pod的虚拟环境的环境标Header。这个EnvoyFilter对象正常情况下不应该影响Envoy与Pilot的通信，但之前也有用户反馈过出现类似情况。
 我们在自己的集群里使用Istio 1.4/1.5/1.6都进行过验证，至今尚未复现此问题。
 
可尝试在创建VirtualEnvironment对象的时候，将配置envHeader.autoInject的值设置为false，重新apply到集群，看看问题是否消失。等待亲的反馈~

**Comment by linfan** [comment]
初步估计是由于EnvoyFilter对象创建过程中抛出异常，导致Envoy Sidecar未能正常初始化，已经较长时间未有复现案例，Issue先关闭
