### ISSUE TITLE
istio 1.5 & 1.6 没有注入 ISTIO_METAJSON_LABELS 变量，envoyfilter 失效

### ISSUE THREAD

**Issue by cynial** [alibaba/virtual-environment#19]
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L236

istio 1.5 & 1.6 在 `kubectl -n istio-system edit configmap istio-sidecar-injector` 中找不到 `ISTIO_METAJSON_LABELS` 了，会导致依赖 `ISTIO_METAJSON_LABELS` 的 `envoyfilter` 失效

**Comment by linfan** [comment]
1.5以后的版本需要补充安装一个Webhook组件，见文档的[部署说明](https://alibaba.github.io/virtual-environment/#/zh-cn/ve/deployment)的`kubectl apply -f webhooks/virtualenvironment_tag_injector_webhook.yaml`这个步骤。

**Comment by linfan** [comment]
Webhook组件会新注入一个`VIRTUAL_ENVIRONMENT_TAG`变量，替代Istio 1.5版本以前自动注入的`ISTIO_METAJSON_LABELS`变量。
目前是做了兼容，还是先尝试使用`ISTIO_METAJSON_LABELS`，读取不到的时候才用`VIRTUAL_ENVIRONMENT_TAG`，这个兼容在下个版本会去掉，避免造成误解。

**Comment by linfan** [comment]
`ISTIO_METAJSON_LABELS`兼容已移除 8f9ec6fd636c4a66554fb1be8d47f09bfb3b1f9f
