### ISSUE TITLE
【求助】当pod中业务容器为https时，virtual-environment不能解析header中的环境标签了

### ISSUE THREAD

**Issue by pencilcap123** [alibaba/virtual-environment#24]

**Comment by freyrlin** [comment]
这个问题暂时无解，virtual-environment的路由能力当前基于Istio组件，但Istio组件不支持对HTTPS流量进行精细管控

**Comment by linfan** [comment]
这个问题暂时无解，virtual-environment的路由能力当前基于Istio组件，但Istio组件不支持对HTTPS流量进行精细管控

**Comment by linfan** [comment]
virtual-environment与具体Mesh层在设计上是解耦的，目前只做了基于Istio的实现，未来如果有其他支持HTTPS流量控制的Mesh产品，可以进行适配

**Comment by pencilcap123** [comment]
谢了，那就先用http的吧，反正是开发环境，无所谓。期待后续有支持。

**Comment by linfan** [comment]
暂无后续Action，先关闭
