### ISSUE TITLE
测试环境管理中特性环境和公共环境的MQ能否实现隔离？

### ISSUE THREAD

**Issue by ZhangKe4042602** [alibaba/virtual-environment#25]
比如RocketMQ,公共环境中有A,B,C三个服务，消息链路为A->B->C。特性环境中对A,B服务进行开发，分别叫做a,b。当特性环境的a服务发送消息时能否实现链路为a->b->C.其中特性环境和稳定环境调用时都会传递环境标识，接收请求的一端是可以知道服务是从哪个环境请求过来的。这是RocketMQ是怎样进行路由，实现消息消费的隔离呢？避免服务B消费到本应b消费的topic消息呢？

**Comment by linfan** [comment]
目前的Istio或其他类似Mesh技术都还不支持异步消息的路由控制。要实现异步消息隔离有两种可能的方案：
一种是用譬如Dapr这种全托管的Mesh方案，扩展实现异步消息的路由控制。
一种方案是直接广播，改造消息中间件，在接收以后根据环境标保留或丢弃。

**Comment by ZhangKe4042602** [comment]
十分感谢！！！
