### ISSUE TITLE
当配置了一个新的只有一个路由规则的 service 时，virtual-env-operator 会生成一个没有用的 virtualservice。

### ISSUE THREAD

**Issue by qunqiang** [alibaba/virtual-environment#26]
在命名空间下创建了一个新的只有一个路由规则的 service 配置后，virtual-env-operator 会被触发 reconcile 为这个 service 创建一个 virtualservice 路由规则，但是这个路由规则并没有实际的用途，可以增加一个判断 ，对于此类的 service 不再生成 virtualservice.

**Comment by linfan** [comment]
fix in `v0.5.1`
