### ISSUE TITLE
Create virtual-env-operator deployment fail because of new version of  k8s 

### ISSUE THREAD

**Issue by chenweijia0925** [alibaba/virtual-environment#29]
After the new version of k8s is built with Go 1.15 version, it does not support X509 certificates

The following is the error message:
Error creating: Internal error occurred: failed calling webhook "webhook-server.kt-virtual-environment.svc": Post "https://webhook-server.kt-virtual-environment.svc:443/inject?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

**Comment by markWord** [comment]
想问下这个后面怎么解决的？

**Comment by linfan** [comment]
需要更新一下证书生成文档和`kt-env`的Webhook组件默认证书，近期会更新

**Comment by xiongxiaoxx** [comment]
有进展吗？

**Comment by markWord** [comment]
> 有进展吗？

我是这样弄的证书，就ok了
命令：
`openssl req -nodes -new -x509 -days 3650 -keyout ca.key -out ca.crt -subj "/CN=webhook-server.kt-virtual-environment.svc" -config ssl.conf # Generate the private key for the webhook server 
openssl genrsa -out webhook-server-tls.key 2048 # Generate a Certificate Signing Request (CSR) for the private key, and sign it with the private key of the CA. 
openssl req -new -key webhook-server-tls.key -subj "/CN=webhook-server.kt-virtual-environment.svc" \
    | openssl x509 -req -days 3650 -CA ca.crt -CAkey ca.key -CAcreateserial -out webhook-server-tls.crt -extensions req_ext -extfile ssl.conf`

`tls_crt_b64="$(openssl base64 -A < webhook-server-tls.crt)" 
tls_key_b64="$(openssl base64 -A < webhook-server-tls.key)" 
ca_pem_b64="$(openssl base64 -A < ca.crt)"`

ssl.conf文件（无法上传conf文件，后缀改成了txt）：
[ssl.txt](https://github.com/alibaba/virtual-environment/files/6819926/ssl.txt)

**Comment by linfan** [comment]
v0.6.0 已修复
