### ISSUE TITLE
部署了ktenv之后,springsecurity要验证token的接口都校验token失败了,什么情况呀

### ISSUE THREAD

**Issue by ltshun** [alibaba/virtual-environment#35]
![image](https://user-images.githubusercontent.com/28196370/148345339-dfbfc1ec-b32b-45e5-9f1b-d7528e3c0cf8.png)
![image](https://user-images.githubusercontent.com/28196370/148345170-ab0621f4-9394-4f97-b554-d845fe833769.png)
最终401

**Comment by linfan** [comment]
kt-env会给没有环境标的请求自动加当前实例的环境标，而计算jwt token的时候会用到请求的header。

只能通过程序自己识别当前环境，自行提前加环境标header来解决（kt-env检查到请求已经有环境标header就不会再额外增加）
