### ISSUE TITLE
HTTPRoute 对象的Port默认为0，启动就报错了

### ISSUE THREAD

**Issue by xutao1989103** [alibaba/virtual-environment#4]
{"level":"error","ts":1587525909.714508,"logger":"istio_http_router","msg":"Failed to create VirtualService app-go","error":"admission webhook \"validation.istio.io\" denied the request: configuration is invalid: 2 errors occurred:\n\t* port number 0 must be in the range 1..65535\n\t* port number 0 must be in the range

**Comment by linfan** [comment]
暂未复现，怀疑和 #7 相关

**Comment by linfan** [comment]
在Istio 1.5上复现此问题，已在v0.2.1版本修复
