### ISSUE TITLE
test case 5 always failed, EnvoyFilter not work

### ISSUE THREAD

**Issue by xutao1989103** [alibaba/virtual-environment#5]
Real response: [springboot @ dev] <-empty, [go @ dev] <-empty, [node @ dev] <-empty
Expectation  : [springboot @ dev] <-dev, [go @ dev] <-dev, [node @ dev] <-empty

server.js

 const reqEnvMark = req.headers[envMarkKey] ? req.headers[envMarkKey] : 'empty';

    const headers = {};
    if (req.headers[envMarkKey]) {
        headers[envMarkKey] = reqEnvMark;
    }

看起来并没有透传，reqEnvMark应该还是empty

**Comment by xutao1989103** [comment]
EnvoyFilter demo-virtualenv 添加成功，并成功同步到数据平面，但是append header不成功。

**Comment by linfan** [comment]
@xutao1989103 可能是append操作出错了，用这个命令查一下app-js的sidecar容器在访问的时候有没什么可疑的日志？
```
kubectl logs app-go-dev-5798b746b5-vbsj5 $(kubectl get pod -l app=app-js -l virtual-env=dev -o jsonpath='{.items[0].metadata.name}')  istio-proxy | grep error
```

**Comment by xutao1989103** [comment]
0.0.0.0_9080: script load error: [string "..."]:6: bad argument #1 to 'find' (string expected, got nil)
0.0.0.0_8383: script load error: [string "..."]:6: bad argument #1 to 'find' (string expected, got nil)
10.1.183.212_15030: script load error: [string "..."]:6: bad argument #1 to 'find' (string expected, got nil)

**Comment by xutao1989103** [comment]
> 0.0.0.0_9080: script load error: [string "..."]:6: bad argument #1 to 'find' (string expected, got nil)
> 0.0.0.0_8383: script load error: [string "..."]:6: bad argument #1 to 'find' (string expected, got nil)
> 10.1.183.212_15030: script load error: [string "..."]:6: bad argument #1 to 'find' (string expected, got nil)

感觉是没有ISTIO_METAJSON_LABELS 这个环境变量，lua脚本报错

**Comment by linfan** [comment]
@xutao1989103 看起来直接原因就是`ISTIO_METAJSON_LABELS`变量不存在，这个变量是Istio自动注入到Sidecar容器上的，用下面这个命令看看实际有注入哪些环境变量呢？
```
kubectl get pod '随意一个有Sidecar的Pod名字' -o yaml | grep 'ISTIO_'
```

我这儿的看到的是这些：
```
    - name: ISTIO_META_POD_PORTS
    - name: ISTIO_META_CLUSTER_ID
    - name: ISTIO_META_POD_NAME
    - name: ISTIO_META_CONFIG_NAMESPACE
    - name: ISTIO_META_INTERCEPTION_MODE
    - name: ISTIO_META_INCLUDE_INBOUND_PORTS
    - name: ISTIO_METAJSON_ANNOTATIONS
    - name: ISTIO_METAJSON_LABELS
    - name: ISTIO_META_WORKLOAD_NAME
    - name: ISTIO_META_OWNER
```

**Comment by xutao1989103** [comment]
![image](https://user-images.githubusercontent.com/7332560/80688175-fdf0d800-8afd-11ea-9c56-2e82e71c5dd7.png)

**Comment by linfan** [comment]
Istio 1.5以后把`ISTIO_METAJSON_LABELS`变量移除了，预计在v0.3版本里能修复这个问题

**Comment by linfan** [comment]
功能已在v0.2.2中发布。
相关文档会在v0.3版本一起补充。
