### ISSUE TITLE
重启后，VirtualEnvironment 没变，fetchVirtualEnvIns 返回error

### ISSUE THREAD

**Issue by xutao1989103** [alibaba/virtual-environment#6]
if shared.VirtualEnvIns != request.Name {
		// new virtual environment found
                //重启后VirtualEnvIns这个值为""，但是VirtualEnvironment实际并没有变化
		if shared.VirtualEnvIns != "" {
			// there is an old virtual environment exist
			logger.Info("New VirtualEnv resource detected, deleting " + shared.VirtualEnvIns)
			r.deleteVirtualEnv(request.Namespace, shared.VirtualEnvIns, logger)
		}
		shared.VirtualEnvIns = request.Name
		logger.Info("VirtualEnv added", "Spec", virtualEnv.Spec)
		return virtualEnv, shared.VirtualEnvChangedError{}
	}
	return virtualEnv, nil

**Comment by linfan** [comment]
@xutao1989103 是重启了什么，VirtualEnvironment Operator的Pod么？

**Comment by xutao1989103** [comment]
是的，重启Operator

**Comment by linfan** [comment]
重启Operator会重新分析当前Namespace的环境内容，和首次启动时候会经过相同的代码路径。这里的VirtualEnvChangedError只是为了抛出一个检测到新VIrtualEnvironment对象的的信号，并不是一个真正的逻辑错误，已将类型更名为VirtualEnvChangeDetected
